Repository emelyne1234/wch-prep, pull requests merged in 2024-11, with the labels that each got.

#3 Working on card and chat
  package.json
  pnpm-lock.yaml
  src/app/projects/[id]/page.tsx
  src/assets/animal.jpg
  src/components/dashboard/card/ProjectCard.tsx
  src/components/dashboard/constant.ts
  src/components/ui/accordion.tsx
  tailwind.config.js
Labels: enhancement

#5 implement admin features and make sure it works
  package.json
  pnpm-lock.yaml
  src/app/projects/[id]/page.tsx
  src/app/projects/monitor/page.tsx
  src/app/resources/page.tsx
  src/components/Drawers.tsx
  src/components/Header.tsx
  src/components/dashboard/card/ProjectCard.tsx
  src/components/dashboard/constant.ts
  src/components/projects/Sidebar.tsx
  src/components/ui/Drawer.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/dialog.tsx
  src/components/ui/popover.tsx
  src/types/next-auth.d.ts
Labels: ready

#10 fixing the rich edit issues
  package.json
  pnpm-lock.yaml
  src/components/dashboard/CreateResource.tsx
Labels: bug

#13 Ft/integrate resources
  package.json
  pnpm-lock.yaml
  src/app/api/resources/[id]/route.ts
  src/app/api/resources/route.ts
  src/app/resources/[id]/page.tsx
  src/app/resources/page.tsx
  src/components/dashboard/Create.tsx
  src/components/dashboard/CreateResource.tsx
  src/components/dashboard/card/ProjectCard.tsx
  src/components/dashboard/card/UserProjectCard.tsx
  src/hooks/useResource.ts
  src/server/db/schema.ts
  src/types/resource.ts
Labels: ready
